config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'

  resources :surveys, only: %i[index new create show] do
    resources :responses, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :survey
  validates :answer, inclusion: { in: [true, false] }
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :responses, dependent: :destroy
  validates :question, presence: true, length: { maximum: 150 }

  scope :with_response_data, lambda {
    select(
      'surveys.*,' +
      ' COUNT(responses.id) AS total_count,' +
      ' COUNT(CASE WHEN responses.answer = true THEN 1 END) * 100.0 / ' +
      ' CASE WHEN COUNT(responses.id) = 0 THEN 1 ELSE COUNT(responses.id) END AS yes_percentage,' +
      ' COUNT(CASE WHEN responses.answer = false THEN 1 END) * 100.0 / ' +
      ' CASE WHEN COUNT(responses.id) = 0 THEN 1 ELSE COUNT(responses.id) END AS no_percentage'
    )
      .left_joins(:responses)
      .group('surveys.id')
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    @survey = Survey.find(params[:survey_id])
    @response = @survey.responses.new(response_params)

    if @response.save
      redirect_to @survey, notice: 'Your response has been recorded.'
    else
      render 'surveys/show', status: :unprocessable_entity
    end
  end

  private

  def response_params
    params.require(:response).permit(:answer)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    @surveys = Survey.with_response_data.order(created_at: :desc)
  end

  def new
    @survey = Survey.new
  end

  def show
    @survey = Survey.find_by(id: params[:id])
    if @survey
      @response = @survey.responses.new
      @yes_count = @survey.responses.where(answer: true).count
      @no_count = @survey.responses.where(answer: false).count
    else
      redirect_to surveys_path, alert: 'Survey not found.'
    end
  end

  def create
    @survey = Survey.new(survey_params)

    if @survey.save
      redirect_to surveys_path, notice: 'Survey was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def survey_params
    params.require(:survey).permit(:question)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SurveyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
        crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
        crossorigin="anonymous"></script>
  </body>
</html>

app/views/responses/create.html.erb
<h1>Responses#create</h1>
<p>Find me in app/views/responses/create.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">The following errors prevented the form from being saved:</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/surveys/_back_button.html.erb
<div class="row mb-4">
  <div class="col text-center">
    <%= link_to '← All Surveys', surveys_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/surveys/create.html.erb
<h1>Survey Created!</h1>
<p>Your survey "<%= @survey.question %>" was successfully created.</p>
<%= link_to 'View Survey', survey_path(@survey) %>
<%= link_to 'Back to Surveys', surveys_path %>

app/views/surveys/index.html.erb
<div class="text-center my-5">
  <h1 class="big-bold-title">Surveys</h1>
</div>

<div class="mb-extra text-center mb-5">
  <%= link_to 'Create New Survey', new_survey_path, class: 'btn dark-blue-button text-white' %>
</div>

<div class="container pb-5">
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-4">
    <% @surveys.each do |survey| %>
      <div class="col">
        <div class="card dark-green-card d-flex flex-column">
          <div class="card-body flex-grow-1">
            <h5 class="card-title">
              <%= link_to survey.question, survey_path(survey), class: 'stretched-link text-white text-decoration-none' %>
            </h5>
          </div>
          <div class="card-footer bg-transparent text-center">
            <span class="text-white">Yes: <%= '%.1f' % survey.yes_percentage %>%</span>
            <span class="mx-2">|</span>
            <span class="text-white">No: <%= '%.1f' % survey.no_percentage %>%</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="container mt-5">
  <%= render 'back_button' %>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header text-center">
          <h1>Create New Survey</h1>
        </div>
        <div class="card-body">
          <%= form_with(model: @survey, local: true) do |form| %>
            <%= render 'shared/error_messages', object: @survey %>

            <div class="form-group">
              <%= form.label :question, class: 'form-label' %>
              <%= form.text_field :question, id: :survey_question, class: 'form-control', maxlength: '150' %>
            </div>

            <div class="form-group text-center mt-3">
              <%= form.submit 'Save', class: 'btn btn-success btn-lg px-5 py-2' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/surveys/show.html.erb
<div class="container mt-5">

  <%= render 'back_button' %>

  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card dark-green-card d-flex flex-column">
        <div class="card-body flex-grow-1">
          <h5 class="card-title text-center text-white">
            <%= @survey.question %>
          </h5>
        </div>
        <div class="card-footer bg-transparent text-center">
            <span class="text-white">Yes: <%= @yes_count %></span>
            <span class="mx-2">|</span>
            <span class="text-white">No: <%= @no_count %></span>
        </div>
      </div>
    </div>
  </div>

    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <%= form_with(model: [@survey, Response.new], local: true) do |form| %>
            <div class="form-group d-flex justify-content-center my-3">
                <label class="btn btn-outline-success mr-2 answer-btn-space">
                <%= form.radio_button :answer, true, class: "form-check-input" %>
                Yes
                </label>
                <label class="btn btn-outline-danger ml-2">
                <%= form.radio_button :answer, false, class: "form-check-input" %>
                No
                </label>
            </div>
            <div class="form-group text-center">
                <%= form.submit 'Submit Response', class: 'btn dark-blue-button text-white' %>
            </div>
            <% end %>
        </div>
    </div>
</div>